/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mariogrip_electrumbitcoinwallet_PythonWrapper */

#ifndef _Included_com_mariogrip_electrumbitcoinwallet_PythonWrapper
#define _Included_com_mariogrip_electrumbitcoinwallet_PythonWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mariogrip_electrumbitcoinwallet_PythonWrapper
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mariogrip_electrumbitcoinwallet_PythonWrapper_start
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_mariogrip_electrumbitcoinwallet_PythonWrapper
 * Method:    end
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mariogrip_electrumbitcoinwallet_PythonWrapper_end
  (JNIEnv *, jclass);

/*
 * Class:     com_mariogrip_electrumbitcoinwallet_PythonWrapper
 * Method:    quarry
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mariogrip_electrumbitcoinwallet_PythonWrapper_quarry
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
